Implement previous context marks (add to jump list on m' / m`)
VSCodeVim/Vim pull request #6174
Opened 2021-02-20 05:56 UTC by jose-elias-alvarez

**What this PR does / why we need it**:
Implements previous context marks as described in Vim's `help m'` / `` help m` ``.

**Which issue(s) this PR fixes**
https://github.com/VSCodeVim/Vim/issues/4873

**Special notes for your reviewer**:
First contribution to the project, so please let me know if there's anything I can do differently. Thanks!

2021-02-22 17:18 UTC, J-Fields commented on src/jumps/jumpTracker.ts
> +  public recordJump(from: Jump, to: Jump | null) {
Use `undefined` instead of `null` please

2021-02-22 17:23 UTC, J-Fields commented on test/historyTracker.test.ts
> +    test('can set previous context mark from single quote', () => {
Could you also add a test in `jumpTracker.test.ts`?

2021-02-22 17:25 UTC, J-Fields requested changes
Thanks a bunch! LGTM other than those few nits

2021-02-24 15:09 UTC, jose-elias-alvarez commented
Thanks for the feedback! I changed the type and added a test.

2021-03-01 20:17 UTC, merged

2021-03-01 20:17 UTC, J-Fields commented
Thanks!