Implement `cwindow`/`lwindow` + their prev/next (file) commands
VSCodeVim/Vim pull request #8078
Opened 2022-11-04 18:22 UTC by mogelbrod

**What this PR does / why we need it**:

- Map quickfix commands (`:c`...) to markers/problems panel
- Map location list commands (`:l`...) to comments panel
- Add a wrapper to make it easy to quickly map excommands to vscode commands

Caveats / discussion topics:
1. `cnfile`/`cpfile` and `cn`/`cp` are identical, the vscode commands either:
    - navigates within the current file (editor.action.marker.next)
    - navigates each marker for all files (editor.action.marker.nextInFiles) = _the approach I went with as it seems to best align with `cn`/`cp`_
3. `lnext[f]`/`lprev[f]` doesn't navigate across files - the vscode commands doesn't seem to support it.
4. `cwindow` and `lwindow` do not close their respective panels if there are no items in their list. This felt like a reasonable compromise to avoid complicating the implementation.
5. `cclose` and `lclose` close the primary panel - not specifically their respective panel since it's not possible.

**Which issue(s) this PR fixes**

Fixes #3158

**Special notes for your reviewer**:

Feel free to suggest alternatives to the chosen excommand <> vscode command mappings!

2022-11-08 02:17 UTC, J-Fields requested changes

2022-11-08 08:55 UTC, mogelbrod commented on src/vimscript/exCommandParser.ts
> +function executeVsCodeCommand(command: string, ...args: unknown[]) {
That was my initial thinking as well, but doesn't the command need to call `succeed()` as well? The reasoning behind having a single function handle this was to minimize the noise in all of the repeated code. I'm open for doing it though, but for clarification which signature do you suggest?

```ts
// current
[['cope', 'n'], executeVsCodeCommand('workbench.panel.markers.view.focus')],
// 1
[['cope', 'n'], succeed(new VsCodeCommand('workbench.panel.markers.view.focus'))],
// 2
[['cope', 'n'], VsCodeCommand.explicit('workbench.panel.markers.view.focus')], // .explicit() calls succeed() automatically
// 3
[['cope', 'n'], succeed(VsCodeCommand.explicit('workbench.panel.markers.view.focus'))],
// or something else?
```

2022-11-09 21:30 UTC, J-Fields commented on src/vimscript/exCommandParser.ts
> +function executeVsCodeCommand(command: string, ...args: unknown[]) {
Oh, right - I think `succeed(new VsCodeCommand(...))` is my preference

2022-12-15 15:51 UTC, mogelbrod commented on src/vimscript/exCommandParser.ts
> +function executeVsCodeCommand(command: string, ...args: unknown[]) {
Do you have time to take another look @J-Fields? Sorry for the inconvenience!

2022-12-28 02:18 UTC, merged

2022-12-28 02:18 UTC, J-Fields commented
Much appreciated!