add :m[ove]
VSCodeVim/Vim pull request #8323
Opened 2023-03-20 07:46 UTC by zhanyi22333

**What this PR does / why we need it**:
Add "move" excommand.
For excommand like : a,bmc  (a,b,c are line numbers), it works as follow:
1. Copy text in range [a,b].
2. Paste text below c, in range[c+1,c+1+(b-a)].
3. delete text in  range [a,b].

Futhermore, I just ban the situation that range [a,b] and range[c+1,c+1+(b-a)], which will lead to wrong performance and has no practical use. I also ban the situation that move [a,b] to [a,b], in which case the "move" excommand just do useless work.

**Special notes for your reviewer**:
I'm just a newbie in PR.Let me know if there is something not in convention.

2023-03-20 23:35 UTC, J-Fields requested changes

2023-03-20 23:35 UTC, J-Fields commented on src/cmd_line/commands/move.ts
Can you write a few test cases for `:move` please?

2023-03-21 02:05 UTC, zhanyi22333 commented on src/cmd_line/commands/move.ts
Ok.I'll work on this.
By the way,ls there any doc for writing test or a good sample test script?

2023-03-21 03:33 UTC, J-Fields commented on src/cmd_line/commands/move.ts
`sort.test.ts` is a decent example

2023-03-21 07:04 UTC, zhanyi22333 commented
I've add a test script for m[ove].During the process, I compare its behavior with orignal vim and find some misunderstanding. So I change the workflow and also change the ban situation.
Now, the performannce is finetuned like this:
For excommand like : a,bmc (a,b,c are line numbers), it works as follow:

1. Copy text in range [a,b].
2. Find target position  by c and decide cursor position.
3. Delete text in range [a,b].
4. Paste text to target positon and move cursor to cursor position.

Ban the situtations that  move a range into itself and the situations that move to adress just right abow or below the range.

All test scripts are passed on my pc. If there are some problems with the added test script, let me know. Thanks.

2023-03-22 00:47 UTC, zhanyi22333 commented
There are two tests failed when build on windows-lastest. I've re-test on my pc and can not reproduce them. And the failed tests seem no relationship with m[ove]. I feel confused. Should I do something for the failed tests?

2023-03-22 04:09 UTC, J-Fields commented
> Should I do something for the failed tests?

Nah don't worry about it; a few tests are just flaky

2023-03-22 04:13 UTC, J-Fields approved these changes
Thanks!

2023-03-22 04:15 UTC, merged

2023-03-22 06:15 UTC, Miigon commented
Thank god this is implemented!